# Generated by Django 5.1.5 on 2025-02-04 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='')),
                ('sha_256', models.CharField(max_length=64, unique=True)),
                ('file_size', models.BigIntegerField()),
                ('status', models.IntegerField(choices=[(1, 'infected'), (0, 'Clean')])),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'NOT_UPLOADED'), (2, 'PENDING'), (3, 'SCANNED'), (4, 'NOTIFIED')])),
                ('av_name', models.CharField(max_length=255, unique=True)),
                ('tracking_id', models.BigIntegerField()),
                ('short_result', models.IntegerField(choices=[(1, 'infected'), (0, 'Clean')])),
                ('final_result', models.JSONField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan', to='scanner.scanfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
