# Generated by Django 5.1.5 on 2025-02-08 11:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_alter_scan_final_result_alter_scan_short_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='checked_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
