# Generated by Django 5.1.5 on 2025-02-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_scan_checked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='av_name',
            field=models.CharField(max_length=255),
        ),
    ]
