# Generated by Django 5.1.5 on 2025-02-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_alter_scan_av_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='tracking_id',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
