# Generated by Django 5.1.5 on 2025-02-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0007_alter_scan_short_result_alter_scan_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
